# -*- coding: utf-8 -*-
"""KazanclarinEtkisi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOUGcHi364NUux5VY1Dc8Dht_KjTOU4w
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Parametreler

m     = 10.0   # Robot kütlesi
b     = 5.0    # Sürtünme katsayısı
Kp    = 10.0   # Oransal kazanç
Ki    = 5.0    # İntegral kazancı
Kd    = 1.5    # Türev kazancı

hedef = 1.0    # Referans hız
dt    = 0.01   # Zaman adımı
sure  = 10.0   # Simülasyon süresi


zaman_ekseni = np.arange(0, sure + dt, dt)
n_adim = len(zaman_ekseni)

hiz_listesi = np.zeros(n_adim)  #hız değerleri dizisi

#farklı kp,ki ve kd değerleri için fonksiyon yazma
def karsilastirma(Kp, Ki, Kd):
    hizlar = np.zeros(len(zaman_ekseni))
    v, integral, prev_hata = 0.0, 0.0, 0.0
    for i in range(len(zaman_ekseni)):
        hata = hedef - v
        integral += hata * dt
        turev = (hata - prev_hata) / dt if i > 0 else 0.0
        u = Kp * hata + Ki * integral + Kd * turev
        dv = (u - b * v) / m
        v += dv * dt
        hizlar[i] = v
        prev_hata = hata
    return hizlar

# Farklı Kontrolör Senaryoları
y_p   = karsilastirma(Kp=10, Ki=0,  Kd=0)
y_pi  = karsilastirma(Kp=10, Ki=5,  Kd=0)
y_pd  = karsilastirma(Kp=10, Ki=0,  Kd=1.5)
y_pid = karsilastirma(Kp=10, Ki=5,  Kd=1.5)

# Grafik Çizimi
plt.figure(figsize=(10, 6))
plt.plot(zaman_ekseni, y_p,   label='P Kontrol (Kp=10)',  color='y')
plt.plot(zaman_ekseni, y_pi,  label='PI Kontrol (Kp=10, Ki=5)', color='b')
plt.plot(zaman_ekseni, y_pd,  label='PD Kontrol (Kp=10, Kd=5)', color='g')
plt.plot(zaman_ekseni, y_pid, label='PID Kontrol (Kp=10, Ki=5, Kd=1.5)', linewidth=2, color='m')
plt.axhline(y=hedef, color='r', linestyle=':', label='Referans')
plt.title("Kontrolör Tiplerinin Karşılaştırılması")
plt.xlabel("Zaman (s)"); plt.ylabel("Hız (m/s)")
plt.legend();
plt.grid(True)
plt.show()