# -*- coding: utf-8 -*-
"""Referans Hız Takibi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZuRU0NQMkBUxazKQghY_y5wtEIQDH_CO
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

m     = 10.0   # Robot kütlesi
b     = 5.0    # Sürtünme katsayısı
Kp    = 10.0   # Oransal kazanç
Ki    = 5.0    # İntegral kazancı
Kd    = 1.5    # Türev kazancı

hedef = 1.0    # Referans hız
dt    = 0.01   # Zaman adımı
sure  = 10.0   # Simülasyon süresi


zaman_ekseni = np.arange(0, sure + dt, dt)
n_adim = len(zaman_ekseni)

hiz_listesi = np.zeros(n_adim)
kuvvet_listesi = np.zeros(n_adim)

v = 0.0 #hız değerlerinin tutulacağı değişken
integral = 0.0  #sistemin hata payını tutan değişken
prev_hata = 0.0  #önceki hata değerini tutan değişken

for i in range(n_adim):
    t = zaman_ekseni[i]
    hiz_listesi[i] = v

    hata = hedef - v

    integral += hata * dt

    # İlk adımda (i=0) eğer bu adım uyglanmazsa ilk başta hata payı çok yüksek çıkıyor 0.s de
    turev = (hata - prev_hata) / dt if i > 0 else 0.0

    # Kontrol Sinyali (Kuvvet - F(t))
    u = Kp * hata + Ki * integral + Kd * turev

    #F(t)
    kuvvet_listesi[i] = u

    #ivme
    dv = (u - b * v) / m

    # Hız güncelleme
    v = v + dv * dt
    prev_hata = hata

v_max = np.max(hiz_listesi)
hız_asma_orani = (v_max - hedef)*100

#yukselsuresi tespiti
t_10_idx = np.where(hiz_listesi >= 0.1 * hedef)[0][0]
t_90_idx = np.where(hiz_listesi >= 0.9 * hedef)[0][0]
yukselme_suresi = zaman_ekseni[t_90_idx] - zaman_ekseni[t_10_idx]
t_10_zaman = zaman_ekseni[t_10_idx]
t_90_zaman = zaman_ekseni[t_90_idx]

tolerans = 0.02 * hedef
disarida_kalanlar = np.where(np.abs(hiz_listesi - hedef) > tolerans)[0]
if len(disarida_kalanlar) > 0:
    # Tolerans bandı dışındaki son indeksi bul ve bir sonraki zamanı al
    yerlesme_suresi = zaman_ekseni[disarida_kalanlar[-1] + 1]
else:
    yerlesme_suresi = 0.0

e_ss = np.abs(hedef - hiz_listesi[-1])

performans_ozet = {
    "Performans Kriteri": [
        "Hedef Hız ",
        "Maksimum Hız",
        "Aşma %",
        "Yükselme Süresi",
        "Yükselme Süre Başlangıcı (%10)" ,
        "Yükselme Süre Sonu (%90)",
        "Yerleşme Süresi (%2 Tolerans)",
        "Kalıcı Durum Hatası"
    ],
    "Değer": [
        f"{hedef} m/s",
        f"{v_max:.4f} m/s",
        f"%{hız_asma_orani:.5f}",
        f"{yukselme_suresi:.2f} s",
        f"{t_10_zaman:.2f} s",
        f"{t_90_zaman:.2f} s",
        f"{yerlesme_suresi:.2f} s",
        f"{e_ss:.5f} m/s"
    ]
}

#excele almak ve tablo olarak değerleri göstermek için
df_performans = pd.DataFrame(performans_ozet)
print(df_performans.to_string(index=False))
df_performans.to_excel("performans_ozet.xlsx", index=False)


print("\n" + "="*40)
print(f"{'PERFORMANS ÖZETİ':^40}")
print("="*40)
print(f"{'Hedef Hız:':<25} {hedef} m/s")
print(f"{'Ulaşılan Maks. Hız:':<25} {v_max:.4f} m/s")
print("-" * 40)

#Grafik
plt.figure(figsize=(12, 6))
plt.plot(zaman_ekseni, hiz_listesi, color="blue", linewidth=2, label=f'Robot Hızı (PID) - Kp = {Kp}, Ki = {Ki}, Kd = {Kd}')
plt.axhline(hedef, color="red", linestyle="--", label="Hedef Hız")
plt.annotate(f'Yerleşme Süresi: {yerlesme_suresi:.2f}s',
             xy=(yerlesme_suresi, hedef),
             xytext=(yerlesme_suresi + 1, hedef - 0.2),
             arrowprops=dict(facecolor='black', arrowstyle='->'))
plt.axhline(hedef * 1.02, color="orange", linestyle=":", alpha=0.6, label="±%2 Tolerans")
plt.axhline(hedef * 0.98, color="orange", linestyle=":", alpha=0.6)
plt.axvspan(t_10_zaman, t_90_zaman, color='green', alpha=0.2, label='Yükselme Süresi Aralığı')
plt.xlim(0, sure+1)
plt.ylim(0, max(hiz_listesi) + 0.25)
plt.xticks(np.arange(0, (sure+1), 1))
plt.yticks(np.arange(0, (max(hiz_listesi) + 0.25), 0.1))
plt.xlabel("Zaman (s)")
plt.ylabel("Hız (m/s)")
plt.title("Referans Hız Takibi")
plt.legend()
plt.grid(True, which='both', linestyle='--', alpha=0.5)
plt.show()